services:
  mysql:
    image: "mysql:8.1"
    environment:
      MYSQL_ROOT_PASSWORD: apolo9494
      MYSQL_ROOT_HOST: '%'  # Allow connections from any host
      MYSQL_DATABASE: 'abarrotesWeb'
    volumes:
      - "mysql-vol:/var/lib/mysql"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 15s
      interval: 15s
      retries: 10
    networks:
      - app-network

  web:
    build: .
    image: pia-abarrotesweb
    environment:
      DATABASE_HOST: mysql  # Add this to specify the MySQL host
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:5000"
    networks:
      - app-network

volumes:
  mysql-vol:

networks:
  app-network:
    driver: bridge