services:
  mysql:
    container_name: mysql
    image: "mysql:8.1"
    environment:
      MYSQL_ROOT_PASSWORD: apolo9494
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'abarrotesWeb'
    volumes:
      - "mysql-vol:/var/lib/mysql"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 15s
      interval: 15s
      retries: 10
  web:
    build: .
    image: abarrotesweb
    depends_on:
       mysql:
          condition: service_healthy
    ports:
      - "8000:8080"
volumes:
  mysql-vol: